// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PassKeep.modeles;

#nullable disable

namespace PassKeep.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260416200438_SeedSuperAdmin2")]
    partial class SeedSuperAdmin2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PassKeep.modeles.DbDictionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dictionnaire");
                });

            modelBuilder.Entity("PassKeep.modeles.PKUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PKUser");
                });

            modelBuilder.Entity("PassKeep.modeles.ProfilConnexion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PKUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceCryptPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceLogin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TypeProfilConnexionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PKUserId");

                    b.HasIndex("TypeProfilConnexionId");

                    b.ToTable("ProfilConnexion");
                });

            modelBuilder.Entity("PassKeep.modeles.TypeProfilConnexion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TypeProfilConnexion");
                });

            modelBuilder.Entity("PassKeep.modeles.ProfilConnexion", b =>
                {
                    b.HasOne("PassKeep.modeles.PKUser", "PKUser")
                        .WithMany()
                        .HasForeignKey("PKUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PassKeep.modeles.TypeProfilConnexion", "TypeProfilConnexion")
                        .WithMany()
                        .HasForeignKey("TypeProfilConnexionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PKUser");

                    b.Navigation("TypeProfilConnexion");
                });
#pragma warning restore 612, 618
        }
    }
}
